apiVersion: apps/v1
kind: Deployment
metadata:
  name: servas
  namespace: demo-project
  labels:
    app: servas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servas
  template:
    metadata:
      labels:
        app: servas
    spec:
      serviceAccountName: servas-sa
      containers:
        - name: servas
          image: beromir/servas:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              # Create directories and set permissions
              mkdir -p /app/storage/logs
              chmod -R 775 /app/storage
              
              # Enable error logging
              echo "error_reporting = E_ALL" > /usr/local/etc/php/conf.d/error-logging.ini
              echo "log_errors = On" >> /usr/local/etc/php/conf.d/error-logging.ini
              echo "error_log = /app/storage/logs/php_errors.log" >> /usr/local/etc/php/conf.d/error-logging.ini
              echo "display_errors = On" >> /usr/local/etc/php/conf.d/error-logging.ini
              
              # Disable MySQL SSL requirement (MariaDB syntax)
              cat << EOF > /etc/my.cnf
              [client]
              ssl=0
              ssl-verify-server-cert=0
              EOF
              
              # Write environment variables to .env file
              cat << EOF > /app/.env
              APP_KEY="${APP_KEY}"
              APP_NAME="${APP_NAME}"
              APP_ENV="${APP_ENV}"
              APP_DEBUG="${APP_DEBUG}"
              APP_URL="${APP_URL}"
              SERVAS_ENABLE_REGISTRATION="${SERVAS_ENABLE_REGISTRATION}"
              DB_CONNECTION="${DB_CONNECTION}"
              DB_HOST="${DB_HOST}"
              DB_PORT="${DB_PORT}"
              DB_DATABASE="${DB_DATABASE}"
              DB_USERNAME="${DB_USERNAME}"
              DB_PASSWORD="${DB_PASSWORD}"
              MYSQL_ATTR_SSL_VERIFY_SERVER_CERT="${MYSQL_ATTR_SSL_VERIFY_SERVER_CERT}"
              DB_SSL="${DB_SSL}"
              DB_SSL_VERIFY="${DB_SSL_VERIFY}"
              SESSION_DRIVER=file
              EOF
              
              # Set proper permissions
              chmod 644 /app/.env
              
              # Install Faker
              composer require fakerphp/faker
              
              # Clear Laravel caches first
              php artisan config:clear
              php artisan cache:clear
              php artisan route:clear
              php artisan view:clear
              
              # Run fresh migrations with seed
              echo "Running database migrations..."
              php artisan migrate:fresh --force --seed
              
              # Start Laravel
              php artisan serve --host=0.0.0.0 --port=80 --verbose
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: servas-env
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: servas-secret
                  key: APP_KEY
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: mariadb
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: servas
            - name: DB_USERNAME
              value: servas
            - name: DB_PASSWORD
              value: servas
            - name: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
              value: "false"
            - name: MYSQL_SSL_REQUIRED
              value: "false"
            - name: DB_SSL
              value: "false"
            - name: DB_SSL_VERIFY
              value: "false"
            - name: MYSQL_SSL
              value: "false"
            - name: DB_OPTIONS_SSL_VERIFY_SERVER_CERT
              value: "false"
            - name: LARAVEL_LOAD_USER
              value: "servas"
            - name: LARAVEL_LOAD_PASSWORD
              value: "servas"
            - name: LARAVEL_LOAD_HOST
              value: "mariadb"
            - name: LARAVEL_LOAD_PORT
              value: "3306"
            - name: LARAVEL_LOAD_DATABASE
              value: "servas"
      #     volumeMounts:
      #       - name: env-file
      #         mountPath: /app/.env
      #         subPath: .env
      # volumes:
      #   - name: env-file
      #     configMap:
      #       name: servas-env
