apiVersion: apps/v1
kind: Deployment
metadata:
  name: servas
  labels:
    app: servas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servas
  template:
    metadata:
      labels:
        app: servas
    spec:
      initContainers:
        - name: wait-for-secret
          image: bitnami/kubectl:latest
          command: ['/bin/sh', '-c']
          args:
            - |
              until kubectl get secret servas-key; do
                echo "Waiting for servas-key secret to be created..."
                sleep 2
              done
      containers:
        - name: servas
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: servas-env
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: servas-key
                  key: APP_KEY
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-file
          configMap:
            name: servas-env
