apiVersion: apps/v1
kind: Deployment
metadata:
  name: servas
  labels:
    app: servas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servas
  template:
    metadata:
      labels:
        app: servas
    spec:
      serviceAccountName: servas-sa
      initContainers:
        - name: wait-for-secret
          image: bitnami/kubectl:latest
          command: ['/bin/sh', '-c']
          args:
            - |
              until kubectl get secret servas-key -n demo-project; do
                echo "Waiting for servas-key secret to be created..."
                sleep 2
              done
        - name: load-schema
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ['/bin/sh', '-c']
          args:
            - |
              # Wait for database to be ready
              until nc -z mariadb 3306; do
                echo "Waiting for MariaDB to be ready..."
                sleep 2
              done
              
              # Load schema using environment variables directly
              mysql -u$DB_USERNAME -p$DB_PASSWORD -h$DB_HOST -P$DB_PORT $DB_DATABASE --ssl-mode=DISABLED < /app/database/schema/mysql-schema.dump
              
              # If the above fails, try with explicit disable flags
              if [ $? -ne 0 ]; then
                echo "First attempt failed, trying with explicit SSL disable..."
                mysql -u$DB_USERNAME -p$DB_PASSWORD -h$DB_HOST -P$DB_PORT $DB_DATABASE --ssl=0 --ssl-verify-server-cert=0 < /app/database/schema/mysql-schema.dump
              fi
          envFrom:
            - configMapRef:
                name: servas-env
      containers:
        - name: servas
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: servas-env
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: servas-key
                  key: APP_KEY
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-file
          configMap:
            name: servas-env
