apiVersion: apps/v1
kind: Deployment
metadata:
  name: servas
  namespace: demo-project
  labels:
    app: servas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servas
  template:
    metadata:
      labels:
        app: servas
    spec:
      serviceAccountName: servas-sa
      containers:
        - name: servas
          image: beromir/servas:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              php artisan config:clear
              php artisan cache:clear
              php artisan serve --host=0.0.0.0 --port=80
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: servas-env
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: servas-secret
                  key: APP_KEY
                  optional: true
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: mariadb
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: servas
            - name: DB_USERNAME
              value: servas
            - name: DB_PASSWORD
              value: servas
            - name: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
              value: "false"
            - name: MYSQL_SSL_REQUIRED
              value: "false"
            - name: DB_SSL
              value: "false"
            - name: DB_SSL_VERIFY
              value: "false"
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-file
          configMap:
            name: servas-env
