apiVersion: batch/v1
kind: Job
metadata:
  name: servas-key-generator
  namespace: demo-project
spec:
  template:
    spec:
      serviceAccountName: key-generator-sa
      containers:
      - name: key-generator
        image: beromir/servas:latest
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - |
          # Generate key
          APP_KEY=$(php artisan key:generate --show --force)
          
          # Install kubectl
          wget -O /bin/kubectl "https://dl.k8s.io/release/$(wget -qO- https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x /bin/kubectl
          
          # Create or update secret
          if ! kubectl get secret servas-secret; then
            kubectl create secret generic servas-secret --from-literal=APP_KEY="$APP_KEY"
          else
            kubectl patch secret servas-secret -p="{\"data\":{\"APP_KEY\":\"$(echo -n $APP_KEY | base64)\"}}"
          fi
          
          # Restart servas deployment
          kubectl rollout restart deployment servas
      restartPolicy: Never 