apiVersion: v1
kind: ServiceAccount
metadata:
  name: key-generator-sa
  namespace: demo-project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-creator
  namespace: demo-project
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["patch", "get", "create", "delete", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: key-generator-secret-creator
  namespace: demo-project
subjects:
- kind: ServiceAccount
  name: key-generator-sa
  namespace: demo-project
roleRef:
  kind: Role
  name: secret-creator
  apiGroup: rbac.authorization.k8s.io 