apiVersion: v1
kind: ServiceAccount
metadata:
  name: servas-sa
  namespace: demo-project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: demo-project
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: servas-secret-reader
  namespace: demo-project
subjects:
- kind: ServiceAccount
  name: servas-sa
  namespace: demo-project
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io 